/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Deliverys;

/**
 *
 * @author angel
 */
public class VAdmistradorNucleo extends javax.swing.JFrame {

  /**
   * Creates new form VAdmistradorNucleo
   */
  public VAdmistradorNucleo() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    btn_salir = new javax.swing.JButton();
    btn_clientes = new javax.swing.JButton();
    btn_transportistas = new javax.swing.JButton();
    btn_encomiendas = new javax.swing.JButton();
    jPanel4 = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    tf_ClientNombre = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    tf_ClientNombre3 = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    tf_ClientNombre4 = new javax.swing.JTextField();
    jLabel9 = new javax.swing.JLabel();
    tf_ClientNombre5 = new javax.swing.JTextField();
    jLabel10 = new javax.swing.JLabel();
    tf_ClientNombre6 = new javax.swing.JTextField();
    jLabel11 = new javax.swing.JLabel();
    tf_ClientNombre7 = new javax.swing.JTextField();
    jLabel12 = new javax.swing.JLabel();
    tf_ClientNombre8 = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();
    tf_ClientNombre9 = new javax.swing.JTextField();
    jPanel3 = new javax.swing.JPanel();
    btn_eliminar = new javax.swing.JButton();
    btn_aceptar = new javax.swing.JButton();
    btn_actualizar = new javax.swing.JButton();
    tf_CodEncomienda = new javax.swing.JTextField();
    btn_BuscarEncomienda = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(34, 40, 49));
    jPanel1.setMaximumSize(new java.awt.Dimension(1080, 720));
    jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
    jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel2.setBackground(new java.awt.Color(57, 62, 70));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setBackground(new java.awt.Color(253, 112, 20));
    jLabel1.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(238, 238, 238));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Menu");
    jLabel1.setOpaque(true);
    jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 80));

    btn_salir.setBackground(new java.awt.Color(204, 0, 0));
    btn_salir.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
    btn_salir.setForeground(new java.awt.Color(238, 238, 238));
    btn_salir.setText("Salir");
    btn_salir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_salirActionPerformed(evt);
      }
    });
    jPanel2.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 180, 60));

    btn_clientes.setBackground(new java.awt.Color(253, 112, 20));
    btn_clientes.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
    btn_clientes.setForeground(new java.awt.Color(34, 40, 49));
    btn_clientes.setText("Nucleos");
    btn_clientes.setBorderPainted(false);
    btn_clientes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_clientesActionPerformed(evt);
      }
    });
    jPanel2.add(btn_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 180, 60));

    btn_transportistas.setBackground(new java.awt.Color(253, 112, 20));
    btn_transportistas.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
    btn_transportistas.setForeground(new java.awt.Color(238, 238, 238));
    btn_transportistas.setText("Empleados");
    btn_transportistas.setBorderPainted(false);
    btn_transportistas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_transportistasActionPerformed(evt);
      }
    });
    jPanel2.add(btn_transportistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 180, 60));

    btn_encomiendas.setBackground(new java.awt.Color(253, 112, 20));
    btn_encomiendas.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
    btn_encomiendas.setForeground(new java.awt.Color(238, 238, 238));
    btn_encomiendas.setText("Direcciones");
    btn_encomiendas.setBorderPainted(false);
    btn_encomiendas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_encomiendasActionPerformed(evt);
      }
    });
    jPanel2.add(btn_encomiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 180, 60));

    jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 720));

    jPanel4.setBackground(new java.awt.Color(57, 62, 70));
    jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel5.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(238, 238, 238));
    jLabel5.setText("JTextField");
    jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 40));

    tf_ClientNombre.setEditable(false);
    tf_ClientNombre.setBackground(new java.awt.Color(238, 238, 238));
    tf_ClientNombre.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_ClientNombre.setForeground(new java.awt.Color(34, 40, 49));
    jPanel4.add(tf_ClientNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 320, 40));

    jLabel6.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(238, 238, 238));
    jLabel6.setText("JTextField");
    jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 290, 40));

    tf_ClientNombre3.setEditable(false);
    tf_ClientNombre3.setBackground(new java.awt.Color(238, 238, 238));
    tf_ClientNombre3.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_ClientNombre3.setForeground(new java.awt.Color(34, 40, 49));
    jPanel4.add(tf_ClientNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 320, 40));

    jLabel7.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(238, 238, 238));
    jLabel7.setText("JTextField");
    jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 290, 40));

    tf_ClientNombre4.setEditable(false);
    tf_ClientNombre4.setBackground(new java.awt.Color(238, 238, 238));
    tf_ClientNombre4.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_ClientNombre4.setForeground(new java.awt.Color(34, 40, 49));
    jPanel4.add(tf_ClientNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 320, 40));

    jLabel9.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(238, 238, 238));
    jLabel9.setText("JTextField");
    jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 290, 40));

    tf_ClientNombre5.setEditable(false);
    tf_ClientNombre5.setBackground(new java.awt.Color(238, 238, 238));
    tf_ClientNombre5.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_ClientNombre5.setForeground(new java.awt.Color(34, 40, 49));
    jPanel4.add(tf_ClientNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 320, 40));

    jLabel10.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel10.setForeground(new java.awt.Color(238, 238, 238));
    jLabel10.setText("JTextField");
    jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 290, 40));

    tf_ClientNombre6.setEditable(false);
    tf_ClientNombre6.setBackground(new java.awt.Color(238, 238, 238));
    tf_ClientNombre6.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_ClientNombre6.setForeground(new java.awt.Color(34, 40, 49));
    jPanel4.add(tf_ClientNombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 320, 40));

    jLabel11.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel11.setForeground(new java.awt.Color(238, 238, 238));
    jLabel11.setText("JTextField");
    jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 290, 40));

    tf_ClientNombre7.setEditable(false);
    tf_ClientNombre7.setBackground(new java.awt.Color(238, 238, 238));
    tf_ClientNombre7.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_ClientNombre7.setForeground(new java.awt.Color(34, 40, 49));
    jPanel4.add(tf_ClientNombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 320, 40));

    jLabel12.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel12.setForeground(new java.awt.Color(238, 238, 238));
    jLabel12.setText("JTextField");
    jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 290, 40));

    tf_ClientNombre8.setEditable(false);
    tf_ClientNombre8.setBackground(new java.awt.Color(238, 238, 238));
    tf_ClientNombre8.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_ClientNombre8.setForeground(new java.awt.Color(34, 40, 49));
    jPanel4.add(tf_ClientNombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 320, 40));

    jLabel13.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel13.setForeground(new java.awt.Color(238, 238, 238));
    jLabel13.setText("JTextField");
    jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 290, 40));

    tf_ClientNombre9.setEditable(false);
    tf_ClientNombre9.setBackground(new java.awt.Color(238, 238, 238));
    tf_ClientNombre9.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_ClientNombre9.setForeground(new java.awt.Color(34, 40, 49));
    jPanel4.add(tf_ClientNombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 320, 40));

    jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 740, 500));

    jPanel3.setBackground(new java.awt.Color(57, 62, 70));
    jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    btn_eliminar.setBackground(new java.awt.Color(253, 112, 20));
    btn_eliminar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    btn_eliminar.setForeground(new java.awt.Color(238, 238, 238));
    btn_eliminar.setText("Eliminar");
    btn_eliminar.setFocusPainted(false);
    btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_eliminarActionPerformed(evt);
      }
    });
    jPanel3.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 130, 40));

    btn_aceptar.setBackground(new java.awt.Color(253, 112, 20));
    btn_aceptar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    btn_aceptar.setForeground(new java.awt.Color(238, 238, 238));
    btn_aceptar.setText("Aceptar");
    btn_aceptar.setFocusPainted(false);
    btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_aceptarActionPerformed(evt);
      }
    });
    jPanel3.add(btn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 40));

    btn_actualizar.setBackground(new java.awt.Color(253, 112, 20));
    btn_actualizar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    btn_actualizar.setForeground(new java.awt.Color(238, 238, 238));
    btn_actualizar.setText("Actualizar");
    btn_actualizar.setFocusPainted(false);
    btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_actualizarActionPerformed(evt);
      }
    });
    jPanel3.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 130, 40));

    jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, 490, 80));

    tf_CodEncomienda.setBackground(new java.awt.Color(57, 62, 70));
    tf_CodEncomienda.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_CodEncomienda.setForeground(new java.awt.Color(238, 238, 238));
    tf_CodEncomienda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    tf_CodEncomienda.setText("Codigo nucleo");
    tf_CodEncomienda.setBorder(null);
    tf_CodEncomienda.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tf_CodEncomiendaMouseClicked(evt);
      }
    });
    jPanel1.add(tf_CodEncomienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 310, 40));

    btn_BuscarEncomienda.setBackground(new java.awt.Color(57, 62, 70));
    btn_BuscarEncomienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/lupa1.png"))); // NOI18N
    btn_BuscarEncomienda.setBorderPainted(false);
    btn_BuscarEncomienda.setFocusPainted(false);
    btn_BuscarEncomienda.setFocusable(false);
    btn_BuscarEncomienda.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_BuscarEncomiendaActionPerformed(evt);
      }
    });
    jPanel1.add(btn_BuscarEncomienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 40, 40));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btn_salirActionPerformed

  private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed

  }//GEN-LAST:event_btn_clientesActionPerformed

  private void btn_transportistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transportistasActionPerformed

  }//GEN-LAST:event_btn_transportistasActionPerformed

  private void btn_encomiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encomiendasActionPerformed

  }//GEN-LAST:event_btn_encomiendasActionPerformed

  private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btn_eliminarActionPerformed

  private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed

  }//GEN-LAST:event_btn_aceptarActionPerformed

  private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btn_actualizarActionPerformed

  private void tf_CodEncomiendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_CodEncomiendaMouseClicked
    if(this.tf_CodEncomienda.getText().equals("Codigo nucleo"))
    this.tf_CodEncomienda.setText("");
  }//GEN-LAST:event_tf_CodEncomiendaMouseClicked

  private void btn_BuscarEncomiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarEncomiendaActionPerformed

  }//GEN-LAST:event_btn_BuscarEncomiendaActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VAdmistradorNucleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VAdmistradorNucleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VAdmistradorNucleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VAdmistradorNucleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VAdmistradorNucleo().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_BuscarEncomienda;
  private javax.swing.JButton btn_aceptar;
  private javax.swing.JButton btn_actualizar;
  private javax.swing.JButton btn_clientes;
  private javax.swing.JButton btn_eliminar;
  private javax.swing.JButton btn_encomiendas;
  private javax.swing.JButton btn_salir;
  private javax.swing.JButton btn_transportistas;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JTextField tf_ClientNombre;
  private javax.swing.JTextField tf_ClientNombre3;
  private javax.swing.JTextField tf_ClientNombre4;
  private javax.swing.JTextField tf_ClientNombre5;
  private javax.swing.JTextField tf_ClientNombre6;
  private javax.swing.JTextField tf_ClientNombre7;
  private javax.swing.JTextField tf_ClientNombre8;
  private javax.swing.JTextField tf_ClientNombre9;
  private javax.swing.JTextField tf_CodEncomienda;
  // End of variables declaration//GEN-END:variables
}
