/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Deliverys;

import CRUD.CRUDBase;
import Conexion.Conexion;

/**
 *
 * @author angel
 */
public class VAdministradorUbicacion extends javax.swing.JFrame {
    Conexion conexion = new Conexion();
    public static CRUD.CRUDBase crud;

  /**
   * Creates new form VAdministradorUbicacion
   */
  public VAdministradorUbicacion() {
    initComponents();
    crud = new CRUDBase(conexion.conectar());
    crud.comboboxPaises(cb_pais);
    cb_pais.addItem("Agregar nuevo");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    btn_salir = new javax.swing.JButton();
    btn_empleados = new javax.swing.JButton();
    btn_encomiendas = new javax.swing.JButton();
    BTN_Nucleos2 = new javax.swing.JButton();
    jPanel4 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    cb_pais = new javax.swing.JComboBox<>();
    cb_estado = new javax.swing.JComboBox<>();
    cb_ciudad = new javax.swing.JComboBox<>();
    agregar = new javax.swing.JButton();
    textCod = new javax.swing.JTextField();
    textNombre = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    btn_eliminar = new javax.swing.JButton();
    btn_aceptar = new javax.swing.JButton();
    btn_actualizar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(34, 40, 49));
    jPanel1.setMaximumSize(new java.awt.Dimension(1080, 720));
    jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
    jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel2.setBackground(new java.awt.Color(57, 62, 70));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setBackground(new java.awt.Color(253, 112, 20));
    jLabel1.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(238, 238, 238));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Menu");
    jLabel1.setOpaque(true);
    jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 80));

    btn_salir.setBackground(new java.awt.Color(204, 0, 0));
    btn_salir.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
    btn_salir.setForeground(new java.awt.Color(238, 238, 238));
    btn_salir.setText("Salir");
    btn_salir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_salirActionPerformed(evt);
      }
    });
    jPanel2.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 180, 60));

    btn_empleados.setBackground(new java.awt.Color(253, 112, 20));
    btn_empleados.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
    btn_empleados.setForeground(new java.awt.Color(238, 238, 238));
    btn_empleados.setText("Empleados");
    btn_empleados.setBorderPainted(false);
    btn_empleados.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_empleadosActionPerformed(evt);
      }
    });
    jPanel2.add(btn_empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 180, 60));

    btn_encomiendas.setBackground(new java.awt.Color(253, 112, 20));
    btn_encomiendas.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
    btn_encomiendas.setForeground(new java.awt.Color(34, 40, 49));
    btn_encomiendas.setText("Direcciones");
    btn_encomiendas.setBorderPainted(false);
    btn_encomiendas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_encomiendasActionPerformed(evt);
      }
    });
    jPanel2.add(btn_encomiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 180, 60));

    BTN_Nucleos2.setBackground(new java.awt.Color(253, 112, 20));
    BTN_Nucleos2.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
    BTN_Nucleos2.setForeground(new java.awt.Color(238, 238, 238));
    BTN_Nucleos2.setText("Nucleos");
    BTN_Nucleos2.setBorderPainted(false);
    BTN_Nucleos2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BTN_Nucleos2ActionPerformed(evt);
      }
    });
    jPanel2.add(BTN_Nucleos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 180, 60));

    jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 720));

    jPanel4.setBackground(new java.awt.Color(57, 62, 70));
    jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel2.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(238, 238, 238));
    jLabel2.setText("Estados");
    jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 210, 40));

    jLabel5.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(238, 238, 238));
    jLabel5.setText("Paises");
    jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, 40));

    jLabel8.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(238, 238, 238));
    jLabel8.setText("Ciudades");
    jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 220, 40));

    cb_pais.setBackground(new java.awt.Color(238, 238, 238));
    cb_pais.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    cb_pais.setForeground(new java.awt.Color(34, 40, 49));
    cb_pais.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        cb_paisItemStateChanged(evt);
      }
    });
    cb_pais.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cb_paisActionPerformed(evt);
      }
    });
    jPanel4.add(cb_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 210, 40));

    cb_estado.setBackground(new java.awt.Color(238, 238, 238));
    cb_estado.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    cb_estado.setForeground(new java.awt.Color(34, 40, 49));
    cb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primero seleccione un Pais..." }));
    cb_estado.setEnabled(false);
    cb_estado.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        cb_estadoItemStateChanged(evt);
      }
    });
    cb_estado.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cb_estadoActionPerformed(evt);
      }
    });
    jPanel4.add(cb_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 220, 40));

    cb_ciudad.setBackground(new java.awt.Color(238, 238, 238));
    cb_ciudad.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    cb_ciudad.setForeground(new java.awt.Color(34, 40, 49));
    cb_ciudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primero seleccione un Estado..." }));
    cb_ciudad.setEnabled(false);
    cb_ciudad.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        cb_ciudadItemStateChanged(evt);
      }
    });
    jPanel4.add(cb_ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 220, 40));

    agregar.setBackground(new java.awt.Color(253, 112, 20));
    agregar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    agregar.setForeground(new java.awt.Color(238, 238, 238));
    agregar.setText("Agregar");
    agregar.setFocusPainted(false);
    agregar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        agregarActionPerformed(evt);
      }
    });
    jPanel4.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 140, 40));

    textCod.setEditable(false);
    textCod.setBackground(new java.awt.Color(238, 238, 238));
    textCod.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    textCod.setForeground(new java.awt.Color(34, 40, 49));
    jPanel4.add(textCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 320, 40));

    textNombre.setEditable(false);
    textNombre.setBackground(new java.awt.Color(238, 238, 238));
    textNombre.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    textNombre.setForeground(new java.awt.Color(34, 40, 49));
    jPanel4.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 310, 40));

    jLabel3.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(238, 238, 238));
    jLabel3.setText("Codigo");
    jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 320, 40));

    jLabel4.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(238, 238, 238));
    jLabel4.setText("Nombre");
    jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 310, 40));

    jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 740, 400));

    jPanel3.setBackground(new java.awt.Color(57, 62, 70));
    jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    btn_eliminar.setBackground(new java.awt.Color(253, 112, 20));
    btn_eliminar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    btn_eliminar.setForeground(new java.awt.Color(238, 238, 238));
    btn_eliminar.setText("Eliminar");
    btn_eliminar.setFocusPainted(false);
    btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_eliminarActionPerformed(evt);
      }
    });
    jPanel3.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 130, 40));

    btn_aceptar.setBackground(new java.awt.Color(253, 112, 20));
    btn_aceptar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    btn_aceptar.setForeground(new java.awt.Color(238, 238, 238));
    btn_aceptar.setText("Aceptar");
    btn_aceptar.setFocusPainted(false);
    btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_aceptarActionPerformed(evt);
      }
    });
    jPanel3.add(btn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 40));

    btn_actualizar.setBackground(new java.awt.Color(253, 112, 20));
    btn_actualizar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    btn_actualizar.setForeground(new java.awt.Color(238, 238, 238));
    btn_actualizar.setText("Actualizar");
    btn_actualizar.setFocusPainted(false);
    btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_actualizarActionPerformed(evt);
      }
    });
    jPanel3.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 130, 40));

    jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, 490, 80));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btn_salirActionPerformed

  private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed

  }//GEN-LAST:event_btn_clientesActionPerformed

  private void btn_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empleadosActionPerformed
      new VAdministradorEmpleado().setVisible(true);
      this.setVisible(false);
  }//GEN-LAST:event_btn_empleadosActionPerformed

  private void btn_encomiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encomiendasActionPerformed

  }//GEN-LAST:event_btn_encomiendasActionPerformed

  private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed

  }//GEN-LAST:event_btn_aceptarActionPerformed

  private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btn_actualizarActionPerformed

  private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btn_eliminarActionPerformed

    private void cb_paisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_paisItemStateChanged
        
        if (this.cb_pais.getSelectedIndex() > 0) {
            int size= cb_pais.getItemCount()-1;
            if (this.cb_pais.getSelectedIndex()==size) {
                this.cb_estado.removeAllItems();
                this.cb_ciudad.removeAllItems();
                this.textCod.setEditable(true);
                this.textNombre.setEditable(true);
            }else{
                this.cb_estado.removeAllItems();
                this.cb_estado.setEnabled(true);
                String paisito = crud.buscarCodPais(cb_pais.getSelectedItem().toString());
                crud.comboboxEstados(this.cb_estado, paisito);
                this.cb_estado.addItem("Agregar nuevo");
                textCod.setEditable(false);
                textNombre.setEditable(false);
            }
        }
        else {
            this.cb_estado.removeAllItems();
            textCod.setEditable(false);
            textNombre.setEditable(false);
        }
    }//GEN-LAST:event_cb_paisItemStateChanged

    private void cb_paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_paisActionPerformed

    }//GEN-LAST:event_cb_paisActionPerformed

    private void cb_estadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_estadoItemStateChanged
        if (this.cb_estado.getSelectedIndex() > 0) {
            if (cb_estado.getSelectedIndex()==cb_estado.getItemCount()-1) {
                this.textCod.setEditable(true);
                this.textNombre.setEditable(true);
                this.cb_ciudad.removeAllItems();
            }else{
                String paisito = crud.buscarCodPais(this.cb_pais.getSelectedItem().toString());
                String estadito = crud.buscarCodEstado(this.cb_estado.getSelectedItem().toString(), paisito);
                this.cb_ciudad.removeAllItems();
                this.cb_ciudad.setEnabled(true);
                crud.comboboxCiudad(this.cb_ciudad, paisito, estadito);
                this.cb_ciudad.addItem("Agregar nuevo");
                textCod.setEditable(false);
                textNombre.setEditable(false);
            }
        } else {
            this.cb_ciudad.removeAllItems();
        }
    }//GEN-LAST:event_cb_estadoItemStateChanged

    private void cb_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_estadoActionPerformed

    }//GEN-LAST:event_cb_estadoActionPerformed

    private void cb_ciudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_ciudadItemStateChanged
        if (cb_ciudad.getSelectedIndex()==cb_ciudad.getItemCount()-1) {
            textCod.setEditable(true);
            textNombre.setEditable(true);
        }else{
            textCod.setEditable(false);
            textNombre.setEditable(false);
        }
    }//GEN-LAST:event_cb_ciudadItemStateChanged

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        if ((cb_estado.getSelectedIndex()>0)&&(cb_estado.getSelectedIndex()==cb_estado.getItemCount()-1)) {
            crud.insertEstado(crud.buscarCodPais(cb_pais.getSelectedItem().toString()),textCod.getText(), textNombre.getText());
            textCod.setText("");
            textNombre.setText("");
            this.cb_estado.removeAllItems();
            crud.comboboxEstados(cb_estado, crud.buscarCodPais(cb_pais.getSelectedItem().toString()));
            this.cb_estado.addItem("Agregar nuevo");
        }
        if ((cb_pais.getSelectedIndex()>0)&&(cb_pais.getSelectedIndex()==cb_pais.getItemCount()-1)) {
            crud.insertPais(textCod.getText(), textNombre.getText());
            textCod.setText("");
            textNombre.setText("");
            cb_pais.removeAllItems();
            crud.comboboxPaises(cb_pais);
            cb_pais.addItem("Agregar nuevo");
        }
        if ((cb_ciudad.getSelectedIndex()>0)&&(cb_ciudad.getSelectedIndex()==cb_ciudad.getItemCount()-1)) {
            String pais=crud.buscarCodPais(cb_pais.getSelectedItem().toString());
            crud.insertciudades(pais,crud.buscarCodEstado(cb_estado.getSelectedItem().toString(), pais),textCod.getText(), textNombre.getText());
            textCod.setText("");
            textNombre.setText("");
            String paisito = crud.buscarCodPais(this.cb_pais.getSelectedItem().toString());
            String estadito = crud.buscarCodEstado(this.cb_estado.getSelectedItem().toString(), paisito);
            this.cb_ciudad.removeAllItems();
            this.cb_ciudad.setEnabled(true);
            crud.comboboxCiudad(this.cb_ciudad, paisito, estadito);
            this.cb_ciudad.addItem("Agregar nuevo");
        }
        
    }//GEN-LAST:event_agregarActionPerformed

    private void BTN_Nucleos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_Nucleos2ActionPerformed
        // TODO add your handling code here:
      new VAdministradorNucleo().setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_BTN_Nucleos2ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VAdministradorUbicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VAdministradorUbicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VAdministradorUbicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VAdministradorUbicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VAdministradorUbicacion().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton BTN_Nucleos2;
  private javax.swing.JButton agregar;
  private javax.swing.JButton btn_aceptar;
  private javax.swing.JButton btn_actualizar;
  private javax.swing.JButton btn_eliminar;
  private javax.swing.JButton btn_empleados;
  private javax.swing.JButton btn_encomiendas;
  private javax.swing.JButton btn_salir;
  private javax.swing.JComboBox<String> cb_ciudad;
  private javax.swing.JComboBox<String> cb_estado;
  private javax.swing.JComboBox<String> cb_pais;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JTextField textCod;
  private javax.swing.JTextField textNombre;
  // End of variables declaration//GEN-END:variables
    private javax.swing.JButton BTN_Nucleos;
}
