/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Deliverys;

import CRUD.CRUDAdministradorNucleo;
import CRUD.CRUDBase;
import Conexion.Conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class VAdmistradorNucleo extends javax.swing.JFrame {
    
    Conexion conexion = new Conexion();
    CRUDBase datosBase = new CRUDBase(conexion.conectar());
    CRUDAdministradorNucleo crudAdmNucleo = new CRUDAdministradorNucleo(conexion.conectar());
    String cedulaE;
    
  /**
   * Creates new form VAdmistradorNucleo
   */
  public VAdmistradorNucleo() {
    initComponents();
    this.datosBase.comboboxPaises(JCB_cod_pais);
  }
  
  public VAdmistradorNucleo(String cedulaEmp) {
    initComponents();
    cedulaE = cedulaEmp;
    this.datosBase.comboboxPaises(JCB_cod_pais);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        btn_clientes = new javax.swing.JButton();
        btn_transportistas = new javax.swing.JButton();
        btn_encomiendas = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        JLB_cod_nucleo = new javax.swing.JLabel();
        JTF_cod_nucleo = new javax.swing.JTextField();
        JLB_num_telefonoN = new javax.swing.JLabel();
        JTF_num_telefonoN = new javax.swing.JTextField();
        JLB_identificacionE = new javax.swing.JLabel();
        JTF_identificacionE = new javax.swing.JTextField();
        JLB_direccion = new javax.swing.JLabel();
        JCB_cod_pais = new javax.swing.JComboBox<>();
        JCB_cod_estados = new javax.swing.JComboBox();
        JCB_cod_ciudades = new javax.swing.JComboBox<>();
        JLB_nombre_nucleo = new javax.swing.JLabel();
        JTF_nombre_nucleo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_eliminar = new javax.swing.JButton();
        btn_aceptar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        JTF_cod_nucleo_B = new javax.swing.JTextField();
        btn_BuscarEncomienda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 40, 49));
        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(57, 62, 70));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(253, 112, 20));
        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu");
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 80));

        btn_salir.setBackground(new java.awt.Color(204, 0, 0));
        btn_salir.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(238, 238, 238));
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jPanel2.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 180, 60));

        btn_clientes.setBackground(new java.awt.Color(253, 112, 20));
        btn_clientes.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btn_clientes.setForeground(new java.awt.Color(34, 40, 49));
        btn_clientes.setText("Nucleos");
        btn_clientes.setBorderPainted(false);
        btn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientesActionPerformed(evt);
            }
        });
        jPanel2.add(btn_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 180, 60));

        btn_transportistas.setBackground(new java.awt.Color(253, 112, 20));
        btn_transportistas.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btn_transportistas.setForeground(new java.awt.Color(238, 238, 238));
        btn_transportistas.setText("Empleados");
        btn_transportistas.setBorderPainted(false);
        btn_transportistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transportistasActionPerformed(evt);
            }
        });
        jPanel2.add(btn_transportistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 180, 60));

        btn_encomiendas.setBackground(new java.awt.Color(253, 112, 20));
        btn_encomiendas.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        btn_encomiendas.setForeground(new java.awt.Color(238, 238, 238));
        btn_encomiendas.setText("Direcciones");
        btn_encomiendas.setBorderPainted(false);
        btn_encomiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encomiendasActionPerformed(evt);
            }
        });
        jPanel2.add(btn_encomiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 180, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 720));

        jPanel4.setBackground(new java.awt.Color(57, 62, 70));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLB_cod_nucleo.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JLB_cod_nucleo.setForeground(new java.awt.Color(238, 238, 238));
        JLB_cod_nucleo.setText("Codigo :");
        jPanel4.add(JLB_cod_nucleo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 40));

        JTF_cod_nucleo.setBackground(new java.awt.Color(238, 238, 238));
        JTF_cod_nucleo.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JTF_cod_nucleo.setForeground(new java.awt.Color(34, 40, 49));
        jPanel4.add(JTF_cod_nucleo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 320, 40));

        JLB_num_telefonoN.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JLB_num_telefonoN.setForeground(new java.awt.Color(238, 238, 238));
        JLB_num_telefonoN.setText("Número de teléfono :");
        jPanel4.add(JLB_num_telefonoN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 290, 40));

        JTF_num_telefonoN.setBackground(new java.awt.Color(238, 238, 238));
        JTF_num_telefonoN.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JTF_num_telefonoN.setForeground(new java.awt.Color(34, 40, 49));
        jPanel4.add(JTF_num_telefonoN, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 320, 40));

        JLB_identificacionE.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JLB_identificacionE.setForeground(new java.awt.Color(238, 238, 238));
        JLB_identificacionE.setText("Cédula Empleado :");
        jPanel4.add(JLB_identificacionE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 290, 40));

        JTF_identificacionE.setBackground(new java.awt.Color(238, 238, 238));
        JTF_identificacionE.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JTF_identificacionE.setForeground(new java.awt.Color(34, 40, 49));
        jPanel4.add(JTF_identificacionE, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 320, 40));

        JLB_direccion.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JLB_direccion.setForeground(new java.awt.Color(238, 238, 238));
        JLB_direccion.setText(" Dirección :");
        jPanel4.add(JLB_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 290, 40));

        JCB_cod_pais.setBackground(new java.awt.Color(238, 238, 238));
        JCB_cod_pais.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JCB_cod_pais.setForeground(new java.awt.Color(34, 40, 49));
        JCB_cod_pais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCB_cod_paisItemStateChanged(evt);
            }
        });
        JCB_cod_pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_cod_paisActionPerformed(evt);
            }
        });
        jPanel4.add(JCB_cod_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 320, 40));

        JCB_cod_estados.setBackground(new java.awt.Color(238, 238, 238));
        JCB_cod_estados.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JCB_cod_estados.setForeground(new java.awt.Color(34, 40, 49));
        JCB_cod_estados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Primero seleccione un Pais..." }));
        JCB_cod_estados.setEnabled(false);
        JCB_cod_estados.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCB_cod_estadosItemStateChanged(evt);
            }
        });
        JCB_cod_estados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_cod_estadosActionPerformed(evt);
            }
        });
        jPanel4.add(JCB_cod_estados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 320, 40));

        JCB_cod_ciudades.setBackground(new java.awt.Color(238, 238, 238));
        JCB_cod_ciudades.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JCB_cod_ciudades.setForeground(new java.awt.Color(34, 40, 49));
        JCB_cod_ciudades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primero seleccione un Estado..." }));
        JCB_cod_ciudades.setEnabled(false);
        jPanel4.add(JCB_cod_ciudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 320, 40));

        JLB_nombre_nucleo.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JLB_nombre_nucleo.setForeground(new java.awt.Color(238, 238, 238));
        JLB_nombre_nucleo.setText("Nombre :");
        jPanel4.add(JLB_nombre_nucleo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 290, 40));

        JTF_nombre_nucleo.setBackground(new java.awt.Color(238, 238, 238));
        JTF_nombre_nucleo.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JTF_nombre_nucleo.setForeground(new java.awt.Color(34, 40, 49));
        jPanel4.add(JTF_nombre_nucleo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 320, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 740, 500));

        jPanel3.setBackground(new java.awt.Color(57, 62, 70));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_eliminar.setBackground(new java.awt.Color(253, 112, 20));
        btn_eliminar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(238, 238, 238));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setFocusPainted(false);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 130, 40));

        btn_aceptar.setBackground(new java.awt.Color(253, 112, 20));
        btn_aceptar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btn_aceptar.setForeground(new java.awt.Color(238, 238, 238));
        btn_aceptar.setText("Aceptar");
        btn_aceptar.setFocusPainted(false);
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 40));

        btn_actualizar.setBackground(new java.awt.Color(253, 112, 20));
        btn_actualizar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btn_actualizar.setForeground(new java.awt.Color(238, 238, 238));
        btn_actualizar.setText("Actualizar");
        btn_actualizar.setFocusPainted(false);
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 130, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, 490, 80));

        JTF_cod_nucleo_B.setBackground(new java.awt.Color(57, 62, 70));
        JTF_cod_nucleo_B.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JTF_cod_nucleo_B.setForeground(new java.awt.Color(238, 238, 238));
        JTF_cod_nucleo_B.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTF_cod_nucleo_B.setText("Codigo nucleo");
        JTF_cod_nucleo_B.setBorder(null);
        JTF_cod_nucleo_B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTF_cod_nucleo_BMouseClicked(evt);
            }
        });
        jPanel1.add(JTF_cod_nucleo_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 310, 40));

        btn_BuscarEncomienda.setBackground(new java.awt.Color(57, 62, 70));
        btn_BuscarEncomienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/lupa1.png"))); // NOI18N
        btn_BuscarEncomienda.setBorderPainted(false);
        btn_BuscarEncomienda.setFocusPainted(false);
        btn_BuscarEncomienda.setFocusable(false);
        btn_BuscarEncomienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarEncomiendaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_BuscarEncomienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btn_salirActionPerformed

  private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed

  }//GEN-LAST:event_btn_clientesActionPerformed

  private void btn_transportistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transportistasActionPerformed

  }//GEN-LAST:event_btn_transportistasActionPerformed

  private void btn_encomiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encomiendasActionPerformed

  }//GEN-LAST:event_btn_encomiendasActionPerformed

  private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
    // TODO add your handling code here:
    this.crudAdmNucleo.eliminarRegistro(this.JTF_cod_nucleo_B.getText());
    this.JTF_cod_nucleo_B.setText("Codigo de Nucleo");
    this.JTF_cod_nucleo.setText("");
    this.JTF_cod_nucleo.setEnabled(true);
    this.datosBase.comboboxPaises(this.JCB_cod_pais);
    this.JTF_nombre_nucleo.setText("");
    this.JTF_num_telefonoN.setText("");
    this.JTF_identificacionE.setText("");
    this.btn_actualizar.setEnabled(false);
    this.btn_eliminar.setEnabled(false);
    this.btn_aceptar.setEnabled(true);
  }//GEN-LAST:event_btn_eliminarActionPerformed

  private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
      String CodPais = this.datosBase.buscarCodPais(this.JCB_cod_pais.getSelectedItem().toString());
    String CodEstado = this.datosBase.buscarCodEstado(this.JCB_cod_estados.getSelectedItem().toString(),CodPais);
    String CodCiudad = this.datosBase.buscarCodCiudad(CodPais,CodEstado,this.JCB_cod_ciudades.getSelectedItem().toString());
    
    if (this.JTF_cod_nucleo.getText().equals("") && this.JTF_nombre_nucleo.getText().equals("") && this.JTF_num_telefonoN.getText().equals("") && CodPais.equals("") && CodEstado.equals("") && CodCiudad.equals("")) {
      JOptionPane.showMessageDialog(null, "Llene todos los campos");
    }else{
        if(this.JTF_identificacionE.getText().equals(""))
            this.crudAdmNucleo.insertarDatos(this.JTF_cod_nucleo.getText(), this.JTF_nombre_nucleo.getText(), this.JTF_num_telefonoN.getText(), null,CodCiudad,CodEstado,CodPais);
        else
            this.crudAdmNucleo.insertarDatos(this.JTF_cod_nucleo.getText(), this.JTF_nombre_nucleo.getText(), this.JTF_num_telefonoN.getText(), this.JTF_identificacionE.getText(),CodCiudad,CodEstado,CodPais);
    }
  }//GEN-LAST:event_btn_aceptarActionPerformed

  private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
    // TODO add your handling code here:
    String CodPais = this.datosBase.buscarCodPais(this.JCB_cod_pais.getSelectedItem().toString());
    String CodEstado = this.datosBase.buscarCodEstado(this.JCB_cod_estados.getSelectedItem().toString(),CodPais);
    String CodCiudad = this.datosBase.buscarCodCiudad(CodPais,CodEstado,this.JCB_cod_ciudades.getSelectedItem().toString());
    
    if (this.JTF_cod_nucleo.getText().equals("") && this.JTF_nombre_nucleo.getText().equals("") && this.JTF_num_telefonoN.getText().equals("") && CodPais.equals("") && CodEstado.equals("") && CodCiudad.equals("")) {
      JOptionPane.showMessageDialog(null, "Llene todos los campos");
    }else{
        if(this.JTF_identificacionE.getText().equals(""))
            this.crudAdmNucleo.actualizarDatos(this.JTF_cod_nucleo.getText(), this.JTF_nombre_nucleo.getText(), this.JTF_num_telefonoN.getText(), null,CodCiudad,CodEstado,CodPais);
        else
            this.crudAdmNucleo.actualizarDatos(this.JTF_cod_nucleo.getText(), this.JTF_nombre_nucleo.getText(), this.JTF_num_telefonoN.getText(), this.JTF_identificacionE.getText(),CodCiudad,CodEstado,CodPais);
    }
  }//GEN-LAST:event_btn_actualizarActionPerformed

  private void JTF_cod_nucleo_BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTF_cod_nucleo_BMouseClicked
    if(this.JTF_cod_nucleo_B.getText().equals("Codigo nucleo"))
    this.JTF_cod_nucleo_B.setText("");
  }//GEN-LAST:event_JTF_cod_nucleo_BMouseClicked

  private void btn_BuscarEncomiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarEncomiendaActionPerformed
      String[] datosNucleo = new String[7];
    datosNucleo = this.crudAdmNucleo.buscarNucleo(this.JTF_cod_nucleo_B.getText());
    if(!datosNucleo[0].equals(null)){
      this.JTF_cod_nucleo.setText(datosNucleo[0]);
      this.JTF_nombre_nucleo.setText(datosNucleo[1]);
      this.JTF_num_telefonoN.setText(datosNucleo[2]);
      this.JTF_identificacionE.setText(datosNucleo[3]);
      this.btn_actualizar.setEnabled(true);
      this.btn_eliminar.setEnabled(true);
      this.btn_aceptar.setEnabled(false);
      this.JTF_cod_nucleo.setEnabled(false);
      this.JCB_cod_pais.setSelectedItem(this.datosBase.buscarNombPais(datosNucleo[6]));
      this.JCB_cod_estados.setSelectedItem(this.datosBase.buscarNombEstado(datosNucleo[6],datosNucleo[5]));
      this.JCB_cod_ciudades.setSelectedItem(this.datosBase.buscarNombCiudad(datosNucleo[6],datosNucleo[5],datosNucleo[4]));
    } else {
      JOptionPane.showMessageDialog(null,"Nucleo no encontrado");
    }
  }//GEN-LAST:event_btn_BuscarEncomiendaActionPerformed

    private void JCB_cod_paisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCB_cod_paisItemStateChanged
        String paisito = this.datosBase.buscarCodPais(JCB_cod_pais.getSelectedItem().toString());
        if (this.JCB_cod_pais.getSelectedIndex() > 0) {
            this.JCB_cod_estados.removeAllItems();
            this.JCB_cod_estados.setEnabled(true);
            this.datosBase.comboboxEstados(this.JCB_cod_estados, paisito);
        }
        else {
            this.JCB_cod_estados.removeAllItems();
        }
    }//GEN-LAST:event_JCB_cod_paisItemStateChanged

    private void JCB_cod_paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_cod_paisActionPerformed

    }//GEN-LAST:event_JCB_cod_paisActionPerformed

    private void JCB_cod_estadosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCB_cod_estadosItemStateChanged
        if (this.JCB_cod_estados.getSelectedIndex() > 0) {
            String paisito = this.datosBase.buscarCodPais(this.JCB_cod_pais.getSelectedItem().toString());
            String estadito = this.datosBase.buscarCodEstado(this.JCB_cod_estados.getSelectedItem().toString(), paisito);
            this.JCB_cod_ciudades.removeAllItems();
            this.JCB_cod_ciudades.setEnabled(true);
            this.datosBase.comboboxCiudad(this.JCB_cod_ciudades, paisito, estadito);
        } else {
            this.JCB_cod_ciudades.removeAllItems();
        }
    }//GEN-LAST:event_JCB_cod_estadosItemStateChanged

    private void JCB_cod_estadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_cod_estadosActionPerformed

    }//GEN-LAST:event_JCB_cod_estadosActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VAdmistradorNucleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VAdmistradorNucleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VAdmistradorNucleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VAdmistradorNucleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VAdmistradorNucleo().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCB_cod_ciudades;
    private javax.swing.JComboBox JCB_cod_estados;
    private javax.swing.JComboBox<String> JCB_cod_pais;
    private javax.swing.JLabel JLB_cod_nucleo;
    private javax.swing.JLabel JLB_direccion;
    private javax.swing.JLabel JLB_identificacionE;
    private javax.swing.JLabel JLB_nombre_nucleo;
    private javax.swing.JLabel JLB_num_telefonoN;
    private javax.swing.JTextField JTF_cod_nucleo;
    private javax.swing.JTextField JTF_cod_nucleo_B;
    private javax.swing.JTextField JTF_identificacionE;
    private javax.swing.JTextField JTF_nombre_nucleo;
    private javax.swing.JTextField JTF_num_telefonoN;
    private javax.swing.JButton btn_BuscarEncomienda;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_clientes;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_encomiendas;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_transportistas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
