/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Deliverys;

import Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import static Deliverys.VIniciarSesion.cedula;
import java.awt.HeadlessException;

/**
 *
 * @author angel
 */
public class VCliente extends javax.swing.JFrame {

    Conexion conection = new Conexion();
    Connection conexion = conection.conectar();

    /**
     * Creates new form VCliente
     */
    public VCliente() {
        initComponents();
        comboboxPaquetes(cedula, JCB_lista_paquetes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        JLB_cod_pequete = new javax.swing.JLabel();
        JLB_peso_paq = new javax.swing.JLabel();
        JLB_alto_paq = new javax.swing.JLabel();
        JLB_ancho_paq = new javax.swing.JLabel();
        JLB_profundidad = new javax.swing.JLabel();
        JLB_cod_destino = new javax.swing.JLabel();
        JTF_cod_paquete = new javax.swing.JTextField();
        JTF_peso_paq = new javax.swing.JTextField();
        JTF_alto_paq = new javax.swing.JTextField();
        JTF_ancho_paq = new javax.swing.JTextField();
        JTF_profundidad = new javax.swing.JTextField();
        JTF_cod_destino = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JCB_lista_paquetes = new javax.swing.JComboBox<>();
        Btn_Ingresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 40, 49));
        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(57, 62, 70));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLB_cod_pequete.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JLB_cod_pequete.setForeground(new java.awt.Color(238, 238, 238));
        JLB_cod_pequete.setText("Codigo de Paquete :");
        jPanel2.add(JLB_cod_pequete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 250, 40));

        JLB_peso_paq.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JLB_peso_paq.setForeground(new java.awt.Color(238, 238, 238));
        JLB_peso_paq.setText("Peso :");
        jPanel2.add(JLB_peso_paq, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 250, 40));

        JLB_alto_paq.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JLB_alto_paq.setForeground(new java.awt.Color(238, 238, 238));
        JLB_alto_paq.setText("Alto :");
        jPanel2.add(JLB_alto_paq, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 250, 40));

        JLB_ancho_paq.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JLB_ancho_paq.setForeground(new java.awt.Color(238, 238, 238));
        JLB_ancho_paq.setText("Ancho :");
        jPanel2.add(JLB_ancho_paq, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 250, 40));

        JLB_profundidad.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JLB_profundidad.setForeground(new java.awt.Color(238, 238, 238));
        JLB_profundidad.setText("Profundidad :");
        jPanel2.add(JLB_profundidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 250, 40));

        JLB_cod_destino.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JLB_cod_destino.setForeground(new java.awt.Color(238, 238, 238));
        JLB_cod_destino.setText("Codigo de destino :");
        jPanel2.add(JLB_cod_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 250, 40));

        JTF_cod_paquete.setBackground(new java.awt.Color(238, 238, 238));
        JTF_cod_paquete.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JTF_cod_paquete.setForeground(new java.awt.Color(34, 40, 49));
        JTF_cod_paquete.setEnabled(false);
        jPanel2.add(JTF_cod_paquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 300, 40));

        JTF_peso_paq.setBackground(new java.awt.Color(238, 238, 238));
        JTF_peso_paq.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JTF_peso_paq.setForeground(new java.awt.Color(34, 40, 49));
        JTF_peso_paq.setEnabled(false);
        jPanel2.add(JTF_peso_paq, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 300, 40));

        JTF_alto_paq.setBackground(new java.awt.Color(238, 238, 238));
        JTF_alto_paq.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JTF_alto_paq.setForeground(new java.awt.Color(34, 40, 49));
        JTF_alto_paq.setEnabled(false);
        jPanel2.add(JTF_alto_paq, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 300, 40));

        JTF_ancho_paq.setBackground(new java.awt.Color(238, 238, 238));
        JTF_ancho_paq.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JTF_ancho_paq.setForeground(new java.awt.Color(34, 40, 49));
        JTF_ancho_paq.setEnabled(false);
        jPanel2.add(JTF_ancho_paq, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 300, 40));

        JTF_profundidad.setBackground(new java.awt.Color(238, 238, 238));
        JTF_profundidad.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JTF_profundidad.setForeground(new java.awt.Color(34, 40, 49));
        JTF_profundidad.setEnabled(false);
        jPanel2.add(JTF_profundidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 300, 40));

        JTF_cod_destino.setBackground(new java.awt.Color(238, 238, 238));
        JTF_cod_destino.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JTF_cod_destino.setForeground(new java.awt.Color(34, 40, 49));
        JTF_cod_destino.setEnabled(false);
        jPanel2.add(JTF_cod_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 300, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 780, 410));

        jLabel4.setBackground(new java.awt.Color(253, 112, 20));
        jLabel4.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Estado de paquete");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 80));

        JCB_lista_paquetes.setBackground(new java.awt.Color(57, 62, 70));
        JCB_lista_paquetes.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        JCB_lista_paquetes.setForeground(new java.awt.Color(238, 238, 238));
        JCB_lista_paquetes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCB_lista_paquetesItemStateChanged(evt);
            }
        });
        JCB_lista_paquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_lista_paquetesActionPerformed(evt);
            }
        });
        jPanel1.add(JCB_lista_paquetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 370, 40));

        Btn_Ingresar.setBackground(new java.awt.Color(253, 112, 20));
        Btn_Ingresar.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Ingresar.setForeground(new java.awt.Color(238, 238, 238));
        Btn_Ingresar.setText("Salir");
        Btn_Ingresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Btn_Ingresar.setBorderPainted(false);
        Btn_Ingresar.setFocusPainted(false);
        Btn_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_IngresarActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 650, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  private void Btn_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_IngresarActionPerformed

  }//GEN-LAST:event_Btn_IngresarActionPerformed

    private void JCB_lista_paquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_lista_paquetesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_JCB_lista_paquetesActionPerformed

    private void JCB_lista_paquetesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCB_lista_paquetesItemStateChanged
        // TODO add your handling code here:
        if (this.JCB_lista_paquetes.getSelectedIndex() > 0) {
            String paquetico = JCB_lista_paquetes.getSelectedItem().toString();
            String[] datosPaquetes = buscarPaquetes(paquetico);
            this.JTF_cod_paquete.setText(datosPaquetes[0]);
            this.JTF_peso_paq.setText(datosPaquetes[1]);
            this.JTF_alto_paq.setText(datosPaquetes[2]);
            this.JTF_ancho_paq.setText(datosPaquetes[3]);
            this.JTF_profundidad.setText(datosPaquetes[4]);
            this.JTF_cod_destino.setText(datosPaquetes[5]);
        }
    }//GEN-LAST:event_JCB_lista_paquetesItemStateChanged

    /**
     * *******LLENAR COMBOBOX DE ENCOMIENDAS********
     */
    public void comboboxPaquetes(String cedula, JComboBox cb) {

        try {
            String SQL = "SELECT p.cod_paquete FROM Paquetes AS p, Encomiendas AS e, Clientes AS c  "
                    + "WHERE c.identificacionC = ? AND c.identificacionC = e.identificacionC "
                    + "ORDER BY cod_paquete ASC";
            PreparedStatement consulta = conexion.prepareStatement(SQL);
            consulta.setString(1, cedula);
            ResultSet resultado = consulta.executeQuery();
            cb.addItem("Seleccione una opcion");
            while (resultado.next()) {
                cb.addItem(resultado.getString("cod_paquete"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Fallo: " + ex.getMessage());
        }
    }

    //************FUNCION QUE HACE UN STRING ARRAY DE UN PAQUETE************
    public String[] buscarPaquetes(String cod_paquete) {

        String[] datosPaquetes = new String[6];

        try {
            String SQL = "SELECT * FROM Paquetes WHERE cod_paquetes = ?";
            PreparedStatement consulta = this.conexion.prepareStatement(SQL);
            consulta.setString(1, cod_paquete);
            System.out.println("Consulta exitosa");
            ResultSet resultado = consulta.executeQuery();

            while (resultado.next()) {
                datosPaquetes[0] = resultado.getString("cod_paquetes");
                datosPaquetes[1] = resultado.getString("peso_paq");
                datosPaquetes[2] = resultado.getString("alto_paq");
                datosPaquetes[3] = resultado.getString("ancho_paq");
                datosPaquetes[4] = resultado.getString("profundidad");
                datosPaquetes[5] = resultado.getString("cod_destino");
            }
        } catch (HeadlessException | SQLException e) {
            System.out.println("Fallo en la consulta" + e.getMessage());
        }
        
        return datosPaquetes;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Ingresar;
    private javax.swing.JComboBox<String> JCB_lista_paquetes;
    private javax.swing.JLabel JLB_alto_paq;
    private javax.swing.JLabel JLB_ancho_paq;
    private javax.swing.JLabel JLB_cod_destino;
    private javax.swing.JLabel JLB_cod_pequete;
    private javax.swing.JLabel JLB_peso_paq;
    private javax.swing.JLabel JLB_profundidad;
    private javax.swing.JTextField JTF_alto_paq;
    private javax.swing.JTextField JTF_ancho_paq;
    private javax.swing.JTextField JTF_cod_destino;
    private javax.swing.JTextField JTF_cod_paquete;
    private javax.swing.JTextField JTF_peso_paq;
    private javax.swing.JTextField JTF_profundidad;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
