/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Deliverys;

import CRUD.CRUDBase;
import CRUD.CRUDClientes;
import Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import static Deliverys.VIniciarSesion.cedula;
import java.awt.HeadlessException;

/**
 *
 * @author angel
 */
public class VCliente extends javax.swing.JFrame {

    Conexion conexion = new Conexion();
    CRUDClientes CRUDClientes = new CRUDClientes(conexion.conectar());
    CRUDBase datosBase = new CRUDBase(conexion.conectar());

    /**
     * Creates new form VCliente
     */
    public VCliente() {
        initComponents();
        this.CRUDClientes.comboboxEncomiendas(JCB_lista_paquetes, cedula);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    JCB_lista_paquetes = new javax.swing.JComboBox<>();
    Btn_Ingresar = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    jPanel2 = new javax.swing.JPanel();
    JLB_peso_paq = new javax.swing.JLabel();
    JLB_alto_paq = new javax.swing.JLabel();
    JLB_profundidad = new javax.swing.JLabel();
    JLB_cod_destino = new javax.swing.JLabel();
    tf_precio = new javax.swing.JTextField();
    tf_transportista = new javax.swing.JTextField();
    tf_destinatario = new javax.swing.JTextField();
    JLB_cod_destino1 = new javax.swing.JLabel();
    tf_llegada = new javax.swing.JTextField();
    JLB_cod_destino2 = new javax.swing.JLabel();
    tf_salida = new javax.swing.JTextField();
    JLB_cod_destino3 = new javax.swing.JLabel();
    tf_creada = new javax.swing.JTextField();
    JLB_ancho_paq1 = new javax.swing.JLabel();
    tf_estado = new javax.swing.JTextField();
    JLB_ancho_paq = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    ta_destino = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(34, 40, 49));
    jPanel1.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jPanel1.setMaximumSize(new java.awt.Dimension(1080, 720));
    jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
    jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel4.setBackground(new java.awt.Color(253, 112, 20));
    jLabel4.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel4.setText("Estado de paquete");
    jLabel4.setOpaque(true);
    jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 80));

    JCB_lista_paquetes.setBackground(new java.awt.Color(238, 238, 238));
    JCB_lista_paquetes.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    JCB_lista_paquetes.setForeground(new java.awt.Color(34, 40, 49));
    JCB_lista_paquetes.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        JCB_lista_paquetesItemStateChanged(evt);
      }
    });
    JCB_lista_paquetes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        JCB_lista_paquetesActionPerformed(evt);
      }
    });
    jPanel1.add(JCB_lista_paquetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 260, 40));

    Btn_Ingresar.setBackground(new java.awt.Color(253, 112, 20));
    Btn_Ingresar.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
    Btn_Ingresar.setForeground(new java.awt.Color(238, 238, 238));
    Btn_Ingresar.setText("Salir");
    Btn_Ingresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    Btn_Ingresar.setBorderPainted(false);
    Btn_Ingresar.setFocusPainted(false);
    Btn_Ingresar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Btn_IngresarActionPerformed(evt);
      }
    });
    jPanel1.add(Btn_Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 650, 140, 40));

    jPanel2.setBackground(new java.awt.Color(57, 62, 70));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    JLB_peso_paq.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    JLB_peso_paq.setForeground(new java.awt.Color(238, 238, 238));
    JLB_peso_paq.setText("Estado:");
    jPanel2.add(JLB_peso_paq, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 440, 250, 40));

    JLB_alto_paq.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    JLB_alto_paq.setForeground(new java.awt.Color(238, 238, 238));
    JLB_alto_paq.setText("Precio:");
    jPanel2.add(JLB_alto_paq, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 250, 40));

    JLB_profundidad.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    JLB_profundidad.setForeground(new java.awt.Color(238, 238, 238));
    JLB_profundidad.setText("Destinatario:");
    jPanel2.add(JLB_profundidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 250, 40));

    JLB_cod_destino.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    JLB_cod_destino.setForeground(new java.awt.Color(238, 238, 238));
    JLB_cod_destino.setText("Destino:");
    jPanel2.add(JLB_cod_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 250, 40));

    tf_precio.setEditable(false);
    tf_precio.setBackground(new java.awt.Color(238, 238, 238));
    tf_precio.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_precio.setForeground(new java.awt.Color(34, 40, 49));
    jPanel2.add(tf_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 300, 40));

    tf_transportista.setEditable(false);
    tf_transportista.setBackground(new java.awt.Color(238, 238, 238));
    tf_transportista.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_transportista.setForeground(new java.awt.Color(34, 40, 49));
    jPanel2.add(tf_transportista, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 300, 40));

    tf_destinatario.setEditable(false);
    tf_destinatario.setBackground(new java.awt.Color(238, 238, 238));
    tf_destinatario.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_destinatario.setForeground(new java.awt.Color(34, 40, 49));
    jPanel2.add(tf_destinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 300, 40));

    JLB_cod_destino1.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    JLB_cod_destino1.setForeground(new java.awt.Color(238, 238, 238));
    JLB_cod_destino1.setText("Fecha llegada:");
    jPanel2.add(JLB_cod_destino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 250, 40));

    tf_llegada.setBackground(new java.awt.Color(238, 238, 238));
    tf_llegada.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_llegada.setForeground(new java.awt.Color(34, 40, 49));
    tf_llegada.setEnabled(false);
    jPanel2.add(tf_llegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 300, 40));

    JLB_cod_destino2.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    JLB_cod_destino2.setForeground(new java.awt.Color(238, 238, 238));
    JLB_cod_destino2.setText("Fecha salida:");
    jPanel2.add(JLB_cod_destino2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 250, 40));

    tf_salida.setEditable(false);
    tf_salida.setBackground(new java.awt.Color(238, 238, 238));
    tf_salida.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_salida.setForeground(new java.awt.Color(34, 40, 49));
    jPanel2.add(tf_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 300, 40));

    JLB_cod_destino3.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    JLB_cod_destino3.setForeground(new java.awt.Color(238, 238, 238));
    JLB_cod_destino3.setText("Fecha creada:");
    jPanel2.add(JLB_cod_destino3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 250, 40));

    tf_creada.setEditable(false);
    tf_creada.setBackground(new java.awt.Color(238, 238, 238));
    tf_creada.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_creada.setForeground(new java.awt.Color(34, 40, 49));
    jPanel2.add(tf_creada, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 300, 40));

    JLB_ancho_paq1.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    JLB_ancho_paq1.setForeground(new java.awt.Color(238, 238, 238));
    JLB_ancho_paq1.setText("Transportista:");
    jPanel2.add(JLB_ancho_paq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 250, 40));

    tf_estado.setEditable(false);
    tf_estado.setBackground(new java.awt.Color(238, 238, 238));
    tf_estado.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_estado.setForeground(new java.awt.Color(34, 40, 49));
    jPanel2.add(tf_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 300, 40));

    JLB_ancho_paq.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    JLB_ancho_paq.setForeground(new java.awt.Color(238, 238, 238));
    JLB_ancho_paq.setText("Estado:");
    jPanel2.add(JLB_ancho_paq, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 250, 40));

    ta_destino.setEditable(false);
    ta_destino.setBackground(new java.awt.Color(238, 238, 238));
    ta_destino.setColumns(20);
    ta_destino.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    ta_destino.setForeground(new java.awt.Color(34, 40, 49));
    ta_destino.setLineWrap(true);
    ta_destino.setRows(5);
    ta_destino.setCaretColor(new java.awt.Color(255, 255, 255));
    ta_destino.setMinimumSize(new java.awt.Dimension(13, 120));
    jScrollPane1.setViewportView(ta_destino);

    jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 300, 70));

    jScrollPane2.setViewportView(jPanel2);

    jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 800, 460));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void Btn_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_IngresarActionPerformed
    new VIniciarSesion().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_Btn_IngresarActionPerformed

    private void JCB_lista_paquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_lista_paquetesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_JCB_lista_paquetesActionPerformed

    private void JCB_lista_paquetesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCB_lista_paquetesItemStateChanged
      if(this.JCB_lista_paquetes.getSelectedIndex()>0){
        String[] datosEncomiendas = this.CRUDClientes.buscarCliente(cedula, this.JCB_lista_paquetes.getSelectedItem().toString());
        switch(datosEncomiendas[0]){
          case "D": this.tf_estado.setText("Por pagar");
          case "P": this.tf_estado.setText("Por asignar");
          case "T": this.tf_estado.setText("En transito");
          case "A": this.tf_estado.setText("En destino");
          case "R": this.tf_estado.setText("Retirada");
        }
        this.tf_precio.setText(datosEncomiendas[1]);
        this.tf_destinatario.setText(datosEncomiendas[2]);
        this.ta_destino.setText(this.datosBase.buscarNombPais(datosEncomiendas[3])+" - "+this.datosBase.buscarNombEstado(datosEncomiendas[3],datosEncomiendas[4])+" - "+this.datosBase.buscarNombCiudad(datosEncomiendas[3], datosEncomiendas[4], datosEncomiendas[5]));
        String[] nombreTrans = this.CRUDClientes.buscarTransportista(datosEncomiendas[6]);
        this.tf_transportista.setText(nombreTrans[0]+" "+nombreTrans[1]);
        this.tf_creada.setText(datosEncomiendas[7]);
        this.tf_salida.setText(datosEncomiendas[8]);
        this.tf_llegada.setText(datosEncomiendas[9]);
      }
    }//GEN-LAST:event_JCB_lista_paquetesItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCliente().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton Btn_Ingresar;
  private javax.swing.JComboBox<String> JCB_lista_paquetes;
  private javax.swing.JLabel JLB_alto_paq;
  private javax.swing.JLabel JLB_ancho_paq;
  private javax.swing.JLabel JLB_ancho_paq1;
  private javax.swing.JLabel JLB_cod_destino;
  private javax.swing.JLabel JLB_cod_destino1;
  private javax.swing.JLabel JLB_cod_destino2;
  private javax.swing.JLabel JLB_cod_destino3;
  private javax.swing.JLabel JLB_peso_paq;
  private javax.swing.JLabel JLB_profundidad;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTextArea ta_destino;
  private javax.swing.JTextField tf_creada;
  private javax.swing.JTextField tf_destinatario;
  private javax.swing.JTextField tf_estado;
  private javax.swing.JTextField tf_llegada;
  private javax.swing.JTextField tf_precio;
  private javax.swing.JTextField tf_salida;
  private javax.swing.JTextField tf_transportista;
  // End of variables declaration//GEN-END:variables
}
