/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Deliverys;

import CRUD.CRUDEmpleadoArt;
import Conexion.Conexion;


public class VEmpleadoArt extends javax.swing.JFrame {

  Conexion conexion = new Conexion();
  CRUDEmpleadoArt CRUDArticulos = new CRUDEmpleadoArt(conexion.conectar());
  String ciEmpleado;
  String ciTransportista;
  String codEncomienda;
  String codPaquete;
  public VEmpleadoArt() {
    initComponents();
  }
  
  public VEmpleadoArt(String CITrans, String CodEncom, String CodPaq) {
    initComponents();
    ciTransportista = CITrans;
    codEncomienda = CodEncom;
    codPaquete = CodPaq;
    
    this.CRUDArticulos.comboboxCodArticulos(cb_nombreArt, codEncomienda, codPaquete);
    this.tf_codEncomienda.setText(codEncomienda);
    this.tf_codPaquete.setText(codPaquete);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    btn_eliminar = new javax.swing.JButton();
    btn_cancelar = new javax.swing.JButton();
    tf_codPaquete = new javax.swing.JTextField();
    btn_aceptar = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    tf_cantidad = new javax.swing.JTextField();
    tf_precio = new javax.swing.JTextField();
    cb_nombreArt = new javax.swing.JComboBox<>();
    tf_codEncomienda = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(34, 40, 49));
    jPanel1.setMaximumSize(new java.awt.Dimension(1080, 720));
    jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
    jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setBackground(new java.awt.Color(253, 112, 20));
    jLabel1.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(238, 238, 238));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Agregar artículos");
    jLabel1.setOpaque(true);
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 80));

    btn_eliminar.setBackground(new java.awt.Color(253, 112, 20));
    btn_eliminar.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
    btn_eliminar.setForeground(new java.awt.Color(238, 238, 238));
    btn_eliminar.setText("Eliminar");
    btn_eliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 112, 20)));
    btn_eliminar.setBorderPainted(false);
    btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_eliminarActionPerformed(evt);
      }
    });
    jPanel1.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 660, 140, 40));

    btn_cancelar.setBackground(new java.awt.Color(253, 112, 20));
    btn_cancelar.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
    btn_cancelar.setForeground(new java.awt.Color(238, 238, 238));
    btn_cancelar.setText("Cancelar");
    btn_cancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 112, 20)));
    btn_cancelar.setBorderPainted(false);
    btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_cancelarActionPerformed(evt);
      }
    });
    jPanel1.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 660, 140, 40));

    tf_codPaquete.setBackground(new java.awt.Color(57, 62, 70));
    tf_codPaquete.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_codPaquete.setForeground(new java.awt.Color(238, 238, 238));
    tf_codPaquete.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    tf_codPaquete.setEnabled(false);
    jPanel1.add(tf_codPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 290, 40));

    btn_aceptar.setBackground(new java.awt.Color(253, 112, 20));
    btn_aceptar.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
    btn_aceptar.setForeground(new java.awt.Color(238, 238, 238));
    btn_aceptar.setText("Aceptar");
    btn_aceptar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 112, 20)));
    btn_aceptar.setBorderPainted(false);
    btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_aceptarActionPerformed(evt);
      }
    });
    jPanel1.add(btn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 660, 140, 40));

    jPanel2.setBackground(new java.awt.Color(57, 62, 70));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel2.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(238, 238, 238));
    jLabel2.setText("Nombre:");
    jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 250, 40));

    jLabel3.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(238, 238, 238));
    jLabel3.setText("Cantidad:");
    jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 250, 40));

    jLabel4.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(238, 238, 238));
    jLabel4.setText("Precio:");
    jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 250, 40));

    tf_cantidad.setBackground(new java.awt.Color(238, 238, 238));
    tf_cantidad.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_cantidad.setForeground(new java.awt.Color(34, 40, 49));
    tf_cantidad.setEnabled(false);
    jPanel2.add(tf_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 300, 40));

    tf_precio.setBackground(new java.awt.Color(238, 238, 238));
    tf_precio.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_precio.setForeground(new java.awt.Color(34, 40, 49));
    tf_precio.setEnabled(false);
    jPanel2.add(tf_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 300, 40));

    cb_nombreArt.setBackground(new java.awt.Color(238, 238, 238));
    cb_nombreArt.setEditable(true);
    cb_nombreArt.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    cb_nombreArt.setForeground(new java.awt.Color(34, 40, 49));
    cb_nombreArt.setRequestFocusEnabled(true);
    cb_nombreArt.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        cb_nombreArtItemStateChanged(evt);
      }
    });
    cb_nombreArt.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        cb_nombreArtMouseClicked(evt);
      }
    });
    jPanel2.add(cb_nombreArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 300, 40));

    jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 780, 220));

    tf_codEncomienda.setBackground(new java.awt.Color(57, 62, 70));
    tf_codEncomienda.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_codEncomienda.setForeground(new java.awt.Color(238, 238, 238));
    tf_codEncomienda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    tf_codEncomienda.setEnabled(false);
    jPanel1.add(tf_codEncomienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 290, 40));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
    if(!this.cb_nombreArt.getSelectedItem().toString().equals("Seleccione una opcion")){
      this.CRUDArticulos.eliminarDatos(codEncomienda, codPaquete, this.cb_nombreArt.getSelectedItem().toString());
      if(this.cb_nombreArt.getSelectedIndex()>0) {
        this.cb_nombreArt.removeAllItems();
        this.CRUDArticulos.comboboxCodArticulos(cb_nombreArt, codEncomienda, codPaquete);
      }
      this.tf_cantidad.setText("");
      this.tf_precio.setText("");
    }
  }//GEN-LAST:event_btn_eliminarActionPerformed

  private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
    this.dispose();
  }//GEN-LAST:event_btn_cancelarActionPerformed

  private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
    if(!this.cb_nombreArt.getSelectedItem().toString().equals("Seleccione una opcion")){
      this.CRUDArticulos.insertarDatos(codEncomienda, codPaquete, this.cb_nombreArt.getSelectedItem().toString(), this.tf_cantidad.getText(), this.tf_precio.getText());
      if(this.cb_nombreArt.getSelectedIndex()>0) {
        this.cb_nombreArt.removeAllItems();
        this.CRUDArticulos.comboboxCodArticulos(cb_nombreArt, codEncomienda, codPaquete);
      }
      this.tf_cantidad.setText("");
      this.tf_precio.setText("");
    }
  }//GEN-LAST:event_btn_aceptarActionPerformed

  private void cb_nombreArtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_nombreArtItemStateChanged
    if(this.cb_nombreArt.getSelectedIndex()>0){
      Float[] datosPaq = new Float[2];
      datosPaq =this.CRUDArticulos.buscarArticulos(this.cb_nombreArt.getSelectedItem().toString(),codPaquete,codEncomienda);
      this.tf_cantidad.setText(datosPaq[0].toString());
      this.tf_precio.setText(datosPaq[1].toString());
    }
  }//GEN-LAST:event_cb_nombreArtItemStateChanged

  private void cb_nombreArtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_nombreArtMouseClicked
    if(!this.cb_nombreArt.getSelectedItem().toString().equals("Seleccione una opcion")){
      this.cb_nombreArt.setSelectedItem("");
    }
  }//GEN-LAST:event_cb_nombreArtMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VEmpleadoArt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VEmpleadoArt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VEmpleadoArt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VEmpleadoArt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VEmpleadoArt().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_aceptar;
  private javax.swing.JButton btn_cancelar;
  private javax.swing.JButton btn_eliminar;
  private javax.swing.JComboBox<String> cb_nombreArt;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JTextField tf_cantidad;
  private javax.swing.JTextField tf_codEncomienda;
  private javax.swing.JTextField tf_codPaquete;
  private javax.swing.JTextField tf_precio;
  // End of variables declaration//GEN-END:variables
}
