/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Deliverys;

/**
 *
 * @author angel
 */
public class VEmpleadosEncom extends javax.swing.JFrame {

  /**
   * Creates new form VEmpleadosEncom
   */
  public VEmpleadosEncom() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jTextField1 = new javax.swing.JTextField();
    jPanel3 = new javax.swing.JPanel();
    jButton6 = new javax.swing.JButton();
    jButton7 = new javax.swing.JButton();
    jButton8 = new javax.swing.JButton();
    jPanel4 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jTextField2 = new javax.swing.JTextField();
    jTextField3 = new javax.swing.JTextField();
    jTextField4 = new javax.swing.JTextField();
    jTextField5 = new javax.swing.JTextField();
    jTextField6 = new javax.swing.JTextField();
    jTextField7 = new javax.swing.JTextField();
    jTextField8 = new javax.swing.JTextField();
    jLabel9 = new javax.swing.JLabel();
    jTextField9 = new javax.swing.JTextField();
    jButton5 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(34, 40, 49));
    jPanel1.setMaximumSize(new java.awt.Dimension(1080, 720));
    jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
    jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel2.setBackground(new java.awt.Color(57, 62, 70));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setBackground(new java.awt.Color(253, 112, 20));
    jLabel1.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(238, 238, 238));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Menu");
    jLabel1.setOpaque(true);
    jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 80));

    jButton1.setBackground(new java.awt.Color(204, 0, 0));
    jButton1.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
    jButton1.setForeground(new java.awt.Color(238, 238, 238));
    jButton1.setText("Salir");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 180, 60));

    jButton2.setBackground(new java.awt.Color(253, 112, 20));
    jButton2.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
    jButton2.setForeground(new java.awt.Color(238, 238, 238));
    jButton2.setText("Clientes");
    jButton2.setBorderPainted(false);
    jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 180, 60));

    jButton3.setBackground(new java.awt.Color(253, 112, 20));
    jButton3.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
    jButton3.setForeground(new java.awt.Color(238, 238, 238));
    jButton3.setText("Transportistas");
    jButton3.setBorderPainted(false);
    jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 180, 60));

    jButton4.setBackground(new java.awt.Color(253, 112, 20));
    jButton4.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
    jButton4.setForeground(new java.awt.Color(238, 238, 238));
    jButton4.setText("Encomiendas");
    jButton4.setBorderPainted(false);
    jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 180, 60));

    jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 720));

    jTextField1.setBackground(new java.awt.Color(57, 62, 70));
    jTextField1.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jTextField1.setForeground(new java.awt.Color(238, 238, 238));
    jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    jTextField1.setText("jTextField1");
    jTextField1.setBorder(null);
    jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 310, 40));

    jPanel3.setBackground(new java.awt.Color(57, 62, 70));
    jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jButton6.setBackground(new java.awt.Color(253, 112, 20));
    jButton6.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jButton6.setForeground(new java.awt.Color(238, 238, 238));
    jButton6.setText("Eliminar");
    jButton6.setFocusPainted(false);
    jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 130, 40));

    jButton7.setBackground(new java.awt.Color(253, 112, 20));
    jButton7.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jButton7.setForeground(new java.awt.Color(238, 238, 238));
    jButton7.setText("Aceptar");
    jButton7.setFocusPainted(false);
    jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 40));

    jButton8.setBackground(new java.awt.Color(253, 112, 20));
    jButton8.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jButton8.setForeground(new java.awt.Color(238, 238, 238));
    jButton8.setText("Actualizar");
    jButton8.setFocusPainted(false);
    jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 130, 40));

    jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, 490, 80));

    jPanel4.setBackground(new java.awt.Color(57, 62, 70));
    jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel2.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(238, 238, 238));
    jLabel2.setText("jLabel2");
    jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 40));

    jLabel3.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(238, 238, 238));
    jLabel3.setText("jLabel2");
    jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 290, 40));

    jLabel4.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(238, 238, 238));
    jLabel4.setText("jLabel2");
    jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 290, 40));

    jLabel5.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(238, 238, 238));
    jLabel5.setText("jLabel2");
    jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 290, 40));

    jLabel6.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(238, 238, 238));
    jLabel6.setText("jLabel2");
    jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 290, 40));

    jLabel7.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(238, 238, 238));
    jLabel7.setText("jLabel2");
    jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 290, 40));

    jLabel8.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(238, 238, 238));
    jLabel8.setText("jLabel2");
    jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 290, 40));

    jTextField2.setBackground(new java.awt.Color(238, 238, 238));
    jTextField2.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jTextField2.setForeground(new java.awt.Color(34, 40, 49));
    jTextField2.setText("jTextField2");
    jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 320, 40));

    jTextField3.setBackground(new java.awt.Color(238, 238, 238));
    jTextField3.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jTextField3.setForeground(new java.awt.Color(34, 40, 49));
    jTextField3.setText("jTextField2");
    jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 320, 40));

    jTextField4.setBackground(new java.awt.Color(238, 238, 238));
    jTextField4.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jTextField4.setForeground(new java.awt.Color(34, 40, 49));
    jTextField4.setText("jTextField2");
    jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 320, 40));

    jTextField5.setBackground(new java.awt.Color(238, 238, 238));
    jTextField5.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jTextField5.setForeground(new java.awt.Color(34, 40, 49));
    jTextField5.setText("jTextField2");
    jPanel4.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 320, 40));

    jTextField6.setBackground(new java.awt.Color(238, 238, 238));
    jTextField6.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jTextField6.setForeground(new java.awt.Color(34, 40, 49));
    jTextField6.setText("jTextField2");
    jPanel4.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 320, 40));

    jTextField7.setBackground(new java.awt.Color(238, 238, 238));
    jTextField7.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jTextField7.setForeground(new java.awt.Color(34, 40, 49));
    jTextField7.setText("jTextField2");
    jPanel4.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 320, 40));

    jTextField8.setBackground(new java.awt.Color(238, 238, 238));
    jTextField8.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jTextField8.setForeground(new java.awt.Color(34, 40, 49));
    jTextField8.setText("jTextField2");
    jPanel4.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 320, 40));

    jLabel9.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(238, 238, 238));
    jLabel9.setText("jLabel2");
    jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 290, 40));

    jTextField9.setBackground(new java.awt.Color(238, 238, 238));
    jTextField9.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jTextField9.setForeground(new java.awt.Color(34, 40, 49));
    jTextField9.setText("jTextField2");
    jPanel4.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 320, 40));

    jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 740, 500));

    jButton5.setBackground(new java.awt.Color(57, 62, 70));
    jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/lupa1.png"))); // NOI18N
    jButton5.setBorderPainted(false);
    jButton5.setFocusPainted(false);
    jButton5.setFocusable(false);
    jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 40, 40));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VEmpleadosEncom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VEmpleadosEncom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VEmpleadosEncom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VEmpleadosEncom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VEmpleadosEncom().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JButton jButton7;
  private javax.swing.JButton jButton8;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JTextField jTextField4;
  private javax.swing.JTextField jTextField5;
  private javax.swing.JTextField jTextField6;
  private javax.swing.JTextField jTextField7;
  private javax.swing.JTextField jTextField8;
  private javax.swing.JTextField jTextField9;
  // End of variables declaration//GEN-END:variables
}
