/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Deliverys;

import Conexion.Conexion;

/**
 *
 * @author angel
 */
public class VEmpleadoEncom extends javax.swing.JFrame {

  Conexion conexion = new Conexion();
  
  String cedulaE;
  public VEmpleadoEncom() {
    initComponents();
  }
  
  public VEmpleadoEncom(String cedulaEmp) {
    initComponents();
    cedulaE = cedulaEmp;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    btn_clientes = new javax.swing.JButton();
    btn_transportistas = new javax.swing.JButton();
    btn_encomiendas = new javax.swing.JButton();
    tf_CodEncomienda = new javax.swing.JTextField();
    jPanel4 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    tf_CEncomienda = new javax.swing.JTextField();
    jTextField3 = new javax.swing.JTextField();
    tf_CostoTotal = new javax.swing.JTextField();
    tf_ClientEncomienda = new javax.swing.JTextField();
    tf_destinatario = new javax.swing.JTextField();
    tf_RegistradoEmp = new javax.swing.JTextField();
    tf_AsignadoEmp = new javax.swing.JTextField();
    jLabel9 = new javax.swing.JLabel();
    tf_Transportista = new javax.swing.JTextField();
    jLabel10 = new javax.swing.JLabel();
    cb_pais = new javax.swing.JComboBox<>();
    cb_estado = new javax.swing.JComboBox<>();
    cb_ciudad = new javax.swing.JComboBox<>();
    btn_BuscarCliente = new javax.swing.JButton();
    btn_paquetes = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    btn_eliminar = new javax.swing.JButton();
    btn_aceptar = new javax.swing.JButton();
    btn_actualizar = new javax.swing.JButton();
    btn_BuscarEncomienda = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(34, 40, 49));
    jPanel1.setMaximumSize(new java.awt.Dimension(1080, 720));
    jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
    jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel2.setBackground(new java.awt.Color(57, 62, 70));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setBackground(new java.awt.Color(253, 112, 20));
    jLabel1.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(238, 238, 238));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Menu");
    jLabel1.setOpaque(true);
    jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 80));

    jButton1.setBackground(new java.awt.Color(204, 0, 0));
    jButton1.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
    jButton1.setForeground(new java.awt.Color(238, 238, 238));
    jButton1.setText("Salir");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 180, 60));

    btn_clientes.setBackground(new java.awt.Color(253, 112, 20));
    btn_clientes.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
    btn_clientes.setForeground(new java.awt.Color(238, 238, 238));
    btn_clientes.setText("Clientes");
    btn_clientes.setBorderPainted(false);
    btn_clientes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_clientesActionPerformed(evt);
      }
    });
    jPanel2.add(btn_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 180, 60));

    btn_transportistas.setBackground(new java.awt.Color(253, 112, 20));
    btn_transportistas.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
    btn_transportistas.setForeground(new java.awt.Color(238, 238, 238));
    btn_transportistas.setText("Transportistas");
    btn_transportistas.setBorderPainted(false);
    btn_transportistas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_transportistasActionPerformed(evt);
      }
    });
    jPanel2.add(btn_transportistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 180, 60));

    btn_encomiendas.setBackground(new java.awt.Color(253, 112, 20));
    btn_encomiendas.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
    btn_encomiendas.setForeground(new java.awt.Color(34, 40, 49));
    btn_encomiendas.setText("Encomiendas");
    btn_encomiendas.setBorderPainted(false);
    btn_encomiendas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_encomiendasActionPerformed(evt);
      }
    });
    jPanel2.add(btn_encomiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 180, 60));

    jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 720));

    tf_CodEncomienda.setBackground(new java.awt.Color(57, 62, 70));
    tf_CodEncomienda.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_CodEncomienda.setForeground(new java.awt.Color(238, 238, 238));
    tf_CodEncomienda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    tf_CodEncomienda.setText("Codigo encomienda");
    tf_CodEncomienda.setBorder(null);
    jPanel1.add(tf_CodEncomienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 310, 40));

    jPanel4.setBackground(new java.awt.Color(57, 62, 70));
    jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel2.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(238, 238, 238));
    jLabel2.setText("Codigo encomienda");
    jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 290, 40));

    jLabel3.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(238, 238, 238));
    jLabel3.setText("Estatus");
    jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 290, 40));

    jLabel4.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(238, 238, 238));
    jLabel4.setText("Costo total");
    jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 290, 40));

    jLabel5.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(238, 238, 238));
    jLabel5.setText("Cliente");
    jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 40));

    jLabel6.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(238, 238, 238));
    jLabel6.setText("Destinatario");
    jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 290, 40));

    jLabel7.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(238, 238, 238));
    jLabel7.setText("Registrado por:");
    jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 290, 40));

    jLabel8.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(238, 238, 238));
    jLabel8.setText("Asignado por:");
    jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 290, 40));

    tf_CEncomienda.setBackground(new java.awt.Color(238, 238, 238));
    tf_CEncomienda.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_CEncomienda.setForeground(new java.awt.Color(34, 40, 49));
    jPanel4.add(tf_CEncomienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 320, 40));

    jTextField3.setBackground(new java.awt.Color(238, 238, 238));
    jTextField3.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jTextField3.setForeground(new java.awt.Color(34, 40, 49));
    jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 320, 40));

    tf_CostoTotal.setBackground(new java.awt.Color(238, 238, 238));
    tf_CostoTotal.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_CostoTotal.setForeground(new java.awt.Color(34, 40, 49));
    jPanel4.add(tf_CostoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 320, 40));

    tf_ClientEncomienda.setBackground(new java.awt.Color(238, 238, 238));
    tf_ClientEncomienda.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_ClientEncomienda.setForeground(new java.awt.Color(34, 40, 49));
    tf_ClientEncomienda.setEnabled(false);
    jPanel4.add(tf_ClientEncomienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 270, 40));

    tf_destinatario.setBackground(new java.awt.Color(238, 238, 238));
    tf_destinatario.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_destinatario.setForeground(new java.awt.Color(34, 40, 49));
    jPanel4.add(tf_destinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 320, 40));

    tf_RegistradoEmp.setBackground(new java.awt.Color(238, 238, 238));
    tf_RegistradoEmp.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_RegistradoEmp.setForeground(new java.awt.Color(34, 40, 49));
    jPanel4.add(tf_RegistradoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 320, 40));

    tf_AsignadoEmp.setBackground(new java.awt.Color(238, 238, 238));
    tf_AsignadoEmp.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_AsignadoEmp.setForeground(new java.awt.Color(34, 40, 49));
    jPanel4.add(tf_AsignadoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 320, 40));

    jLabel9.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(238, 238, 238));
    jLabel9.setText("Transportista:");
    jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 290, 40));

    tf_Transportista.setBackground(new java.awt.Color(238, 238, 238));
    tf_Transportista.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    tf_Transportista.setForeground(new java.awt.Color(34, 40, 49));
    jPanel4.add(tf_Transportista, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 320, 40));

    jLabel10.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel10.setForeground(new java.awt.Color(238, 238, 238));
    jLabel10.setText("Destino");
    jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 290, 40));

    cb_pais.setBackground(new java.awt.Color(238, 238, 238));
    cb_pais.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    cb_pais.setForeground(new java.awt.Color(34, 40, 49));
    cb_pais.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cb_paisActionPerformed(evt);
      }
    });
    jPanel4.add(cb_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 320, 40));

    cb_estado.setBackground(new java.awt.Color(238, 238, 238));
    cb_estado.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    cb_estado.setForeground(new java.awt.Color(34, 40, 49));
    cb_estado.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cb_estadoActionPerformed(evt);
      }
    });
    jPanel4.add(cb_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 320, 40));

    cb_ciudad.setBackground(new java.awt.Color(238, 238, 238));
    cb_ciudad.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    cb_ciudad.setForeground(new java.awt.Color(34, 40, 49));
    jPanel4.add(cb_ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 320, 40));

    btn_BuscarCliente.setBackground(new java.awt.Color(57, 62, 70));
    btn_BuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/lupa1.png"))); // NOI18N
    btn_BuscarCliente.setBorderPainted(false);
    btn_BuscarCliente.setFocusPainted(false);
    btn_BuscarCliente.setFocusable(false);
    btn_BuscarCliente.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_BuscarClienteActionPerformed(evt);
      }
    });
    jPanel4.add(btn_BuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 40, 40));

    btn_paquetes.setBackground(new java.awt.Color(253, 112, 20));
    btn_paquetes.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    btn_paquetes.setForeground(new java.awt.Color(238, 238, 238));
    btn_paquetes.setText("Paquetes");
    btn_paquetes.setFocusPainted(false);
    btn_paquetes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_paquetesActionPerformed(evt);
      }
    });
    jPanel4.add(btn_paquetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 620, 170, 40));

    jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 740, 700));

    jPanel3.setBackground(new java.awt.Color(57, 62, 70));
    jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    btn_eliminar.setBackground(new java.awt.Color(253, 112, 20));
    btn_eliminar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    btn_eliminar.setForeground(new java.awt.Color(238, 238, 238));
    btn_eliminar.setText("Eliminar");
    btn_eliminar.setFocusPainted(false);
    jPanel3.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 130, 40));

    btn_aceptar.setBackground(new java.awt.Color(253, 112, 20));
    btn_aceptar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    btn_aceptar.setForeground(new java.awt.Color(238, 238, 238));
    btn_aceptar.setText("Aceptar");
    btn_aceptar.setFocusPainted(false);
    jPanel3.add(btn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 40));

    btn_actualizar.setBackground(new java.awt.Color(253, 112, 20));
    btn_actualizar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    btn_actualizar.setForeground(new java.awt.Color(238, 238, 238));
    btn_actualizar.setText("Actualizar");
    btn_actualizar.setFocusPainted(false);
    jPanel3.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 130, 40));

    jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, 490, 80));

    btn_BuscarEncomienda.setBackground(new java.awt.Color(57, 62, 70));
    btn_BuscarEncomienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/lupa1.png"))); // NOI18N
    btn_BuscarEncomienda.setBorderPainted(false);
    btn_BuscarEncomienda.setFocusPainted(false);
    btn_BuscarEncomienda.setFocusable(false);
    btn_BuscarEncomienda.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_BuscarEncomiendaActionPerformed(evt);
      }
    });
    jPanel1.add(btn_BuscarEncomienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 40, 40));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton1ActionPerformed

  private void btn_transportistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transportistasActionPerformed
//    new VEmpleadoTranspo(cedulaE).setVisible(true);
//    this.dispose();
  }//GEN-LAST:event_btn_transportistasActionPerformed

  private void btn_encomiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encomiendasActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btn_encomiendasActionPerformed

  private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed
    new VEmpleadoCliente(cedulaE).setVisible(true);
    this.dispose();
  }//GEN-LAST:event_btn_clientesActionPerformed

  private void cb_paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_paisActionPerformed
    String item = (String)this.cb_pais.getSelectedItem();

    if (item == null) {
      this.cb_estado.setModel(null);
    } else {
      //cargar el combobox con los registros de estados que coincidan con el pais
    }
  }//GEN-LAST:event_cb_paisActionPerformed

  private void cb_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_estadoActionPerformed
    String item = (String)this.cb_estado.getSelectedItem();

    if (item == null) {
      this.cb_ciudad.setModel(null);
    } else {
      //cargar el combobox con los registros de ciudaddes que coincidan con el estado
    }
  }//GEN-LAST:event_cb_estadoActionPerformed

  private void btn_paquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_paquetesActionPerformed

  }//GEN-LAST:event_btn_paquetesActionPerformed

  private void btn_BuscarEncomiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarEncomiendaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btn_BuscarEncomiendaActionPerformed

  private void btn_BuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarClienteActionPerformed
    this.tf_ClientEncomienda.setEnabled(true);
  }//GEN-LAST:event_btn_BuscarClienteActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VEmpleadoEncom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VEmpleadoEncom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VEmpleadoEncom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VEmpleadoEncom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VEmpleadoEncom().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_BuscarCliente;
  private javax.swing.JButton btn_BuscarEncomienda;
  private javax.swing.JButton btn_aceptar;
  private javax.swing.JButton btn_actualizar;
  private javax.swing.JButton btn_clientes;
  private javax.swing.JButton btn_eliminar;
  private javax.swing.JButton btn_encomiendas;
  private javax.swing.JButton btn_paquetes;
  private javax.swing.JButton btn_transportistas;
  private javax.swing.JComboBox<String> cb_ciudad;
  private javax.swing.JComboBox<String> cb_estado;
  private javax.swing.JComboBox<String> cb_pais;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JTextField tf_AsignadoEmp;
  private javax.swing.JTextField tf_CEncomienda;
  private javax.swing.JTextField tf_ClientEncomienda;
  private javax.swing.JTextField tf_CodEncomienda;
  private javax.swing.JTextField tf_CostoTotal;
  private javax.swing.JTextField tf_RegistradoEmp;
  private javax.swing.JTextField tf_Transportista;
  private javax.swing.JTextField tf_destinatario;
  // End of variables declaration//GEN-END:variables
}
