/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Deliverys;

/**
 *
 * @author angel
 */
public class VTransportistaDatos extends javax.swing.JFrame {

  /**
   * Creates new form VTransportistaDatos
   */
  public VTransportistaDatos() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    Btn_Ingresar = new javax.swing.JButton();
    Btn_Ingresar1 = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jTextField2 = new javax.swing.JTextField();
    jTextField3 = new javax.swing.JTextField();
    jTextField4 = new javax.swing.JTextField();
    jTextField5 = new javax.swing.JTextField();
    jTextField6 = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(34, 40, 49));
    jPanel1.setMaximumSize(new java.awt.Dimension(1080, 720));
    jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
    jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel4.setBackground(new java.awt.Color(253, 112, 20));
    jLabel4.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel4.setText("Datos personales");
    jLabel4.setOpaque(true);
    jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 80));

    Btn_Ingresar.setBackground(new java.awt.Color(253, 112, 20));
    Btn_Ingresar.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
    Btn_Ingresar.setForeground(new java.awt.Color(238, 238, 238));
    Btn_Ingresar.setText("Salir");
    Btn_Ingresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    Btn_Ingresar.setBorderPainted(false);
    Btn_Ingresar.setFocusPainted(false);
    Btn_Ingresar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Btn_IngresarActionPerformed(evt);
      }
    });
    jPanel1.add(Btn_Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 640, 140, 40));

    Btn_Ingresar1.setBackground(new java.awt.Color(253, 112, 20));
    Btn_Ingresar1.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
    Btn_Ingresar1.setForeground(new java.awt.Color(238, 238, 238));
    Btn_Ingresar1.setText("Encomiendas");
    Btn_Ingresar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 112, 20)));
    Btn_Ingresar1.setBorderPainted(false);
    Btn_Ingresar1.setFocusPainted(false);
    Btn_Ingresar1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Btn_Ingresar1ActionPerformed(evt);
      }
    });
    jPanel1.add(Btn_Ingresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 640, 140, 40));

    jPanel2.setBackground(new java.awt.Color(57, 62, 70));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(238, 238, 238));
    jLabel1.setText("jLabel1");
    jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 250, 40));

    jLabel2.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(238, 238, 238));
    jLabel2.setText("jLabel1");
    jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 250, 40));

    jLabel3.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(238, 238, 238));
    jLabel3.setText("jLabel1");
    jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 250, 40));

    jLabel5.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(238, 238, 238));
    jLabel5.setText("jLabel1");
    jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 250, 40));

    jLabel6.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(238, 238, 238));
    jLabel6.setText("jLabel1");
    jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 250, 40));

    jLabel7.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(238, 238, 238));
    jLabel7.setText("jLabel1");
    jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 250, 40));

    jTextField1.setBackground(new java.awt.Color(238, 238, 238));
    jTextField1.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jTextField1.setForeground(new java.awt.Color(34, 40, 49));
    jTextField1.setText("jTextField1");
    jTextField1.setEnabled(false);
    jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 300, 40));

    jTextField2.setBackground(new java.awt.Color(238, 238, 238));
    jTextField2.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jTextField2.setForeground(new java.awt.Color(34, 40, 49));
    jTextField2.setText("jTextField1");
    jTextField2.setEnabled(false);
    jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 300, 40));

    jTextField3.setBackground(new java.awt.Color(238, 238, 238));
    jTextField3.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jTextField3.setForeground(new java.awt.Color(34, 40, 49));
    jTextField3.setText("jTextField1");
    jTextField3.setEnabled(false);
    jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 300, 40));

    jTextField4.setBackground(new java.awt.Color(238, 238, 238));
    jTextField4.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jTextField4.setForeground(new java.awt.Color(34, 40, 49));
    jTextField4.setText("jTextField1");
    jTextField4.setEnabled(false);
    jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 300, 40));

    jTextField5.setBackground(new java.awt.Color(238, 238, 238));
    jTextField5.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jTextField5.setForeground(new java.awt.Color(34, 40, 49));
    jTextField5.setText("jTextField1");
    jTextField5.setEnabled(false);
    jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 300, 40));

    jTextField6.setBackground(new java.awt.Color(238, 238, 238));
    jTextField6.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
    jTextField6.setForeground(new java.awt.Color(34, 40, 49));
    jTextField6.setText("jTextField1");
    jTextField6.setEnabled(false);
    jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 300, 40));

    jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 780, 410));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void Btn_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_IngresarActionPerformed

  }//GEN-LAST:event_Btn_IngresarActionPerformed

  private void Btn_Ingresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Ingresar1ActionPerformed

  }//GEN-LAST:event_Btn_Ingresar1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VTransportistaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VTransportistaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VTransportistaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VTransportistaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VTransportistaDatos().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton Btn_Ingresar;
  private javax.swing.JButton Btn_Ingresar1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JTextField jTextField4;
  private javax.swing.JTextField jTextField5;
  private javax.swing.JTextField jTextField6;
  // End of variables declaration//GEN-END:variables
}
