/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Deliverys;

import CRUD.Seguridad;
import Conexion.Conexion;
import static Deliverys.VIniciarSesion.cedula;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class VUsuarios extends javax.swing.JFrame {

    Conexion conexion = new Conexion();
    Seguridad verfUsuario = new Seguridad(conexion.conectar());

    /**
     * Creates new form VUsuarios
     */
    public VUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    Btn_Ingresar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(34, 40, 49));
    jPanel1.setMaximumSize(new java.awt.Dimension(1080, 740));
    jPanel1.setPreferredSize(new java.awt.Dimension(1080, 740));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel4.setBackground(new java.awt.Color(253, 112, 20));
    jLabel4.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel4.setText("Escoger Usuario");
    jLabel4.setOpaque(true);
    jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 80));

    jPanel2.setBackground(new java.awt.Color(57, 62, 70));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jButton1.setBackground(new java.awt.Color(57, 62, 70));
    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/woman.png"))); // NOI18N
    jButton1.setBorder(null);
    jButton1.setBorderPainted(false);
    jButton1.setFocusPainted(false);
    jButton1.setMaximumSize(new java.awt.Dimension(150, 150));
    jButton1.setMinimumSize(new java.awt.Dimension(150, 150));
    jButton1.setPreferredSize(new java.awt.Dimension(150, 150));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

    jButton2.setBackground(new java.awt.Color(57, 62, 70));
    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/man.png"))); // NOI18N
    jButton2.setBorder(null);
    jButton2.setBorderPainted(false);
    jButton2.setFocusPainted(false);
    jButton2.setMaximumSize(new java.awt.Dimension(150, 150));
    jButton2.setMinimumSize(new java.awt.Dimension(150, 150));
    jButton2.setPreferredSize(new java.awt.Dimension(150, 150));
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });
    jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

    jButton3.setBackground(new java.awt.Color(57, 62, 70));
    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/man(1).png"))); // NOI18N
    jButton3.setBorderPainted(false);
    jButton3.setFocusPainted(false);
    jButton3.setFocusable(false);
    jButton3.setMaximumSize(new java.awt.Dimension(150, 150));
    jButton3.setMinimumSize(new java.awt.Dimension(150, 150));
    jButton3.setPreferredSize(new java.awt.Dimension(150, 150));
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });
    jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

    jLabel1.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(238, 238, 238));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Cliente");
    jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 150, 30));

    jLabel2.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(238, 238, 238));
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("Empleado");
    jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 150, 30));

    jLabel3.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(238, 238, 238));
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("Transportista");
    jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 150, 30));

    jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 790, 270));

    Btn_Ingresar.setBackground(new java.awt.Color(253, 112, 20));
    Btn_Ingresar.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
    Btn_Ingresar.setForeground(new java.awt.Color(238, 238, 238));
    Btn_Ingresar.setText("Cerrar Sesión");
    Btn_Ingresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 112, 20)));
    Btn_Ingresar.setBorderPainted(false);
    Btn_Ingresar.setFocusPainted(false);
    Btn_Ingresar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Btn_IngresarActionPerformed(evt);
      }
    });
    jPanel1.add(Btn_Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 660, 140, 40));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void Btn_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_IngresarActionPerformed
    new VIniciarSesion().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_Btn_IngresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (cedula.equals(verfUsuario.buscarEmpleado(cedula))) {
            new VEmpleadoMenu().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Acceso Denegado");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (cedula.equals(verfUsuario.buscarTransportista(cedula))) {
            new VTransportistaDatos().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Acceso Denegado");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (cedula.equals(verfUsuario.buscarCliente(cedula))) {
            new VCliente().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Acceso Denegado");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VUsuarios().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton Btn_Ingresar;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  // End of variables declaration//GEN-END:variables
}
